import { NgModule } from "@angular/core";

import { TuiAxesModule, TuiBarChartModule, TuiBarModule, TuiBarSetModule, TuiLegendItemModule, TuiLineChartModule, TuiLineDaysChartModule, TuiPieChartModule, TuiRingChartModule } from '@taiga-ui/addon-charts';
import { TuiCurrencyPipeModule, TuiInputCVCModule, TuiInputCardModule, TuiInputExpireModule } from '@taiga-ui/addon-commerce';
import { TuiSidebarModule } from '@taiga-ui/addon-mobile';
import { TuiTableModule, TuiTablePaginationModule } from '@taiga-ui/addon-table';
import { TuiActiveZoneModule, TuiLetModule, TuiValidatorModule } from '@taiga-ui/cdk';
import { TuiAlertModule, TuiButtonModule, TuiCalendarModule, TuiDataListModule, TuiDialogModule, TuiErrorModule, TuiExpandModule, TuiFormatNumberPipeModule, TuiGroupModule, TuiHintModule, TuiLabelModule, TuiLinkModule, TuiLoaderModule, TuiModeModule, TuiNotificationModule, TuiRootModule, TuiScrollbarModule, TuiSvgDefsHostModule, TuiSvgModule, TuiTextfieldControllerModule, TuiTooltipModule } from '@taiga-ui/core';
import { TuiHostedDropdownModule, TuiThemeNightModule } from "@taiga-ui/core/components";
import { TuiDropdownModule } from "@taiga-ui/core/directives";
import { TuiAccordionModule, TuiActionModule, TuiAvatarModule, TuiBadgeModule, TuiBadgedContentModule, TuiBreadcrumbsModule, TuiCarouselModule, TuiCheckboxBlockModule, TuiCheckboxLabeledModule, TuiDataListWrapperModule, TuiInputCopyModule, TuiInputCountModule, TuiInputDateModule, TuiInputDateRangeModule, TuiInputDateTimeModule, TuiInputFilesModule, TuiInputInlineModule, TuiInputModule, TuiInputNumberModule, TuiInputPasswordModule, TuiInputPhoneModule, TuiInputRangeModule, TuiInputTagModule, TuiInputTimeModule, TuiInputYearModule, TuiLineClampModule, TuiMarkerIconModule, TuiMultiSelectModule, TuiPaginationModule, TuiProgressModule, TuiPushModule, TuiRadioBlockModule, TuiRadioLabeledModule, TuiSelectModule, TuiStepperModule, TuiTabsModule, TuiTagModule, TuiTextAreaModule, TuiTilesModule, TuiToggleModule } from '@taiga-ui/kit';

@NgModule({

  exports: [
    TuiThemeNightModule,
    TuiProgressModule,
    TuiAccordionModule,
    TuiActionModule,
    TuiActiveZoneModule,
    TuiAlertModule,
    TuiBreadcrumbsModule,
    TuiAvatarModule,
    TuiAxesModule,
    TuiBadgedContentModule,
    TuiInputRangeModule,
    TuiBadgeModule,
    TuiBarChartModule,
    TuiBarModule,
    TuiBarSetModule,
    TuiButtonModule,
    TuiCalendarModule,
    TuiPaginationModule,
    TuiCarouselModule,
    TuiCheckboxBlockModule,
    TuiCheckboxLabeledModule,
    TuiCurrencyPipeModule,
    TuiDataListModule,
    TuiDataListWrapperModule,
    TuiDialogModule,
    TuiDropdownModule,
    TuiErrorModule,
    TuiExpandModule,
    TuiFormatNumberPipeModule,
    TuiGroupModule,
    TuiHintModule,
    TuiHostedDropdownModule,
    TuiInputCardModule,
    TuiInputCopyModule,
    TuiInputCountModule,
    TuiInputCVCModule,
    TuiInputDateModule,
    TuiInputDateRangeModule,
    TuiInputDateTimeModule,
    TuiInputExpireModule,
    TuiInputFilesModule,
    TuiInputInlineModule,
    TuiInputModule,
    TuiInputNumberModule,
    TuiInputPasswordModule,
    TuiInputPhoneModule,
    TuiInputTagModule,
    TuiInputTimeModule,
    TuiInputYearModule,
    TuiLabelModule,
    TuiLegendItemModule,
    TuiLetModule,
    TuiLineChartModule,
    TuiLineClampModule,
    TuiLineDaysChartModule,
    TuiLinkModule,
    TuiLoaderModule,
    TuiMarkerIconModule,
    TuiModeModule,
    TuiMultiSelectModule,
    TuiNotificationModule,
    TuiPieChartModule,
    TuiPushModule,
    TuiRadioBlockModule,
    TuiRadioLabeledModule,
    TuiRingChartModule,
    TuiRootModule,
    TuiScrollbarModule,
    TuiSelectModule,
    TuiSidebarModule,
    TuiStepperModule,
    TuiSvgDefsHostModule,
    TuiSvgModule,
    TuiTableModule,
    TuiTablePaginationModule,
    TuiTabsModule,
    TuiTagModule,
    TuiTextAreaModule,
    TuiTextfieldControllerModule,
    TuiTilesModule,
    TuiToggleModule,
    TuiTooltipModule,
    TuiValidatorModule,
  ]
})
export class TuiUIModule { }
